package org.example.buttons;

public enum ButtonType {
    START_APP,

    ENTER_PANEL,
    STORE_PANEL,
    CART_PANEL,
    ORDERS_PANEL,
    CONTACT_PANEL,
    RECALLS_PANEL,
    EXIT_PANEL,

    AUTHORIZATION,
    REGISTRATION,
    ENTER_GUEST_MODE,
    CONFIRM_AUTH,
    BACK_FROM_AUTH,
    CONFIRM_REG,
    BACK_FROM_REG,
    GUEST_NO,
    GUEST_YES,
    CONFIRM_EXIT_GUEST_MODE,
    EXIT_GUEST_MODE,

    STORE_SETTINGS,
    PAGE_DOWN,
    PAGE_UP,
    ITEM_INFO,
    CLOSE_PRODUCT_INFO,
    ADD_TO_CART,
    DROP_FROM_CART,
    BUY,
    DROP_ALL,

    SEARCH,
    SEARCH_OPTIONS,
    BOOK_OPTION,
    AUTHOR_OPTION,
    GENRE_OPTION,
    ID_OPTION,
    ALL_OPTION
}
